export enum Event {
    
    READY,
    CHANNEL_CREATE,
    CHANNEL_UPDATE,
    CHANNEL_DELETE,
    CHANNEL_PINS_UPDATE,

    GUILD_CREATE,
    GUILD_UPDATE,
    GUILD_DELETE,
    GUILD_BAN_ADD,
    GUILD_BAN_REMOVE,
    GUILD_EMOJIS_UPDATE,
    GUILD_ROLE_CREATE,
    GUILD_ROLE_UPDATE,
    GUILD_ROLE_DELETE,

    INVITE_CREATE,
    INVITE_DELETE,
    VOICE_STATE_UPDATE,
    PRESENCE_UPDATE,
    TYPING_START,

    MESSAGE_REACTION_ADD,
    MESSAGE_REACTION_REMOVE,
    MESSAGE_REACTION_REMOVE_ALL,
    MESSAGE_REACTION_REMOVE_EMOJI,

    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    MESSAGE_DELETE_BULK,

    DIRECT_MESSAGE_CREATE,
    DIRECT_MESSAGE_UPDATE,
    DIRECT_MESSAGE_DELETE,
    DIRECT_MESSAGE_DELETE_BULK,
    DIRECT_CHANNEL_PINS_UPDATE,
    DIRECT_TYPING_START,

}
